- include_vars: '{{ item }}'
  with_first_found:
  - files:
    - "{{ kernel }}-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ kernel }}-{{ ansible_distribution }}.yml"
    - "{{ kernel }}-{{ ansible_os_family }}.yml"
    skip: true
    paths:
    - "{{ role_path }}/vars"

- set_fact:
    all_apt_keys: "{{ all_apt_keys | default([]) }} + {{ apt_keys | default({}) | dict2items }}"
- set_fact:
    all_apt_repos: "{{ all_apt_repos | default([]) }} + {{ apt_repos | default([]) }}"
- set_fact:
    all_packages: "{{ all_packages | default([]) }} + {{ packages | default([]) }}"
