- include_vars: "{{ kernel }}.yml"

- include_vars: '{{ item }}'
  with_first_found:
  - files:
    - "{{ kernel }}-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ kernel }}-{{ ansible_distribution }}.yml"
    - "{{ kernel }}-{{ ansible_os_family }}.yml"
    skip: true
    paths:
    - "{{ role_path }}/vars"

- name: install packages
  when: packages is defined
  become: yes
  package:
    name: "{{ packages }}"
    state: present
    update_cache: yes

- include_tasks: _os_specific.yml
  vars:
    base_task_name: "{{ kernel }}"
