- set_fact:
    all_packages:
    - git
    - jq

- name: appending packages
  include_tasks: _os_tasks.yml
  vars:
    base_task_name: _collect
  loop: "{{ jupyter_kernels }}"
  loop_control:
    loop_var: kernel

- name: yum EPEL and update
  become: yes
  yum:
    name:
    - epel-release
    state: latest
    update_cache: yes

- name: install yum packages
  become: yes
  yum:
    name: "{{ all_packages | default([]) | unique }}"
    state: latest
    update_cache: yes
