- set_fact:
    all_packages:
    - jq

- name: appending packages
  include_tasks: _os_tasks.yml
  vars:
    base_task_name: _collect
  loop: "{{ jupyter_kernels }}"
  loop_control:
    loop_var: kernel

- name: Add apt keys
  become: yes
  apt_key:
    keyserver: "{{ ap.value }}"
    id: "{{ ap.key }}"
  loop: "{{ all_apt_keys | default([]) | unique }}"
  loop_control:
    loop_var: ap

- name: Add repos
  become: yes
  apt_repository:
    repo: "{{ ap }}"
  loop: "{{ all_apt_repos | default([]) | unique }}"
  loop_control:
    loop_var: ap

- name: apt install
  become: yes
  apt:
    name: "{{ all_packages | default([]) | unique }}"
    update_cache: yes
