- name: install Stack
  command: bash -l -c 'curl -sSL https://get.haskellstack.org/ | sh'

- name: clone HaskellR
  git:
    repo: "{{haskellr.repo}}"
    dest: "{{haskellr.dir}}"
    version: "{{haskellr.version}}"
    force: yes

- name: install HaskellR
  command: bash -l -c 'stack install'
  args:
    chdir: "{{haskellr.dir}}"
    creates: "{{ansible_env.HOME}}/.local/bin/H"

- name: install IHaskell to Jupyter
  command: bash -l -c 'stack exec ihaskell install'
  args:
    chdir: "{{haskellr.dir}}"
    creates: "{{ansible_env.HOME}}/.ihaskell"

- name: install stack packages
  command: "bash -l -c 'stack install {{item}}'"
  args:
    chdir: "{{haskellr.dir}}"
  with_items: "{{stack_deps}}"

- name: initialize hoogle
  command: bash -l -c 'stack exec hoogle -- generate'
  args:
    chdir: "{{haskellr.dir}}"
