- include_tasks: _init_each.yml

- name: check installed Stack
  command: bash -l -c 'type stack'
  register: stack_check
  ignore_errors: true

- name: install Stack
  command: bash -l -c 'curl -sSL https://get.haskellstack.org/ | sh'
  when: stack_check is failed

- name: clone IHaskell
  git:
    repo: "{{ ihaskell.repo }}"
    dest: "{{ ihaskell.dir }}"
    version: "{{ ihaskell.version }}"
    force: no

- name: install IHaskell
  command: bash -l -c 'stack install --fast'
  args:
    chdir: "{{ ihaskell.dir }}"
    creates: "{{ ansible_env.HOME }}/.local/bin/ihaskell"

- name: install IHaskell to Jupyter
  command: bash -l -c 'ihaskell install --stack'
  args:
    creates: "{{ ansible_env.HOME }}/.ihaskell"

- name: install stack packages
  command: bash -l -c "stack install {{ stack_deps | join(' ') }}"

- name: initialize hoogle
  command: bash -l -c 'hoogle generate'
  args:
    creates: "{{ ansible_env.HOME }}/.hoogle"
