- include_tasks: _init_each.yml

- name: install R libraries
  become: yes
  command: bash -l -c "Rscript -e 'install.packages(\"{{ item }}\")'"
  loop: "{{ r_libralies }}"

- name: add user for RStudio
  become: yes
  user:
    name: "{{ rstudio_client.username }}"
    password: "{{ rstudio_client.password | password_hash('sha512') }}"

- name: install IRkernel
  become: yes
  command: bash -l -c "Rscript -e 'install.packages(\"IRkernel\")'"

- name: install IR to jupyter
  command: bash -l -c "Rscript -e 'IRkernel::installspec()'"
