- include_tasks: _init_each.yml

- name: download RStudio
  get_url:
    url: "{{ rstudio_server.url }}"
    checksum: "{{ rstudio_server.checksum }}"
    dest: /tmp/rstudio-server.deb
  when: ansible_os_family == 'Debian'

- name: install RStudio
  become: yes
  command: bash -l -c 'yes | gdebi /tmp/rstudio-server.deb'
  when: ansible_os_family == 'Debian'

- name: remove tmp file
  file:
    path: /tmp/rstudio-server.deb
    state: absent
  when: ansible_os_family == 'Debian'

- name: install R libraries
  become: yes
  command: bash -l -c "Rscript -e 'install.packages(\"{{ item }}\")'"
  with_items: "{{ r_libralies }}"

- name: add user for RStudio
  become: yes
  user:
    name: "{{ rstudio_client.username }}"
    password: "{{ rstudio_client.password | password_hash('sha512') }}"

- name: install IRkernel
  become: yes
  command: bash -l -c "Rscript -e 'install.packages(\"IRkernel\")'"

- name: install IR to jupyter
  command: bash -l -c "Rscript -e 'IRkernel::installspec()'"
